site_name: Template
site_author: Uncle_drew
repo_url: https://github.com/Drew233
site_url: https://github.com/Drew233
site_description: My own template.
theme:
  language: 'zh'
  feature:
    tabs: true
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
    font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
    include_search_page: false
    search_index_only: true

extra:
  search:
    language: 'zh'
  social:
    - type: 'github'
      link: 'https://github.com/Drew233'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_css:
  - '_static/extra.css'


nav:
    - 介绍: index.md
    - 关于: about.md
    - 数学:
        - 素数: math/prime.md
        - 快速幂: math/poww.md
        - 大数: math/bign.md
        - 斐波那契(大数): math/Fibo.md
    - 字符串:
        - 最长回文字串: string/Manacher.md
    - 图论:
        - 最小生成树: Graph/kruskal.md
    - 搜索:
        - BFS: search/bfs.md
        - DFS: search/dfs.md
    - 动态规划:
        - 编辑距离: dp/distance.md
        - 最长公共子序列: dp/LS.md
        - 最长递增子序列: dp/LIS.md
        - 最大子段和: dp/Maxsum.md
        - 换零钱(背包): dp/pack.md
    - 几何:
        - 求多边形面积: geometric/s.md

extra_javascript:
  - 'https://cdn.jsdelivr.net/gh/ethantw/Han@3.3.0/dist/han.min.js'
  - '_static/js/extra.js?v=10'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'


extra_css:
  - 'https://cdn.jsdelivr.net/npm/ah@1.5.0/han.min.css'
  - '_static/css/extra.css?v=11'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
